[BUGFIX] fix typoscript-condition for TYPO3 >= V9.5
bitmotion/static-info-tables-ko pull request #3
Opened 2021-06-15 14:36 UTC by vte-udg

An outdated typoscript-condition is throwing an error in the log for TYPO3 >= 9.5
`component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"language = *ko*"}`
Similar to other static_info_tables-extensions, I've added two versions, one for V9 and up, one for V8 and below

2021-06-15 15:55 UTC, flossels commented
Hi,

thanks for this PR. Since the latest release supports TYPO3 v9 or v10 only, we do not need the TypoScript file for TYPO3 v8. May you please remove this? I will than transfer this fix to other static_info_tables_* extensions owned by us.

Thanks once more :)

2021-06-15 15:58 UTC, flossels requested changes
Since this extension does not support TYPO3 v8 the condition and the second TypoScript file is obsolete.

2021-06-17 14:52 UTC, vte-udg commented
Done :)
This message is really filling up the log since it gets logged every time you switch between pages in the backend.

2021-06-17 17:05 UTC, flossels approved these changes

2021-06-17 17:05 UTC, merged

2021-06-17 17:06 UTC, flossels commented
Thank you :)